FORMAT: 1A
HOST: https://ops.epo.org

# OPS v3.2 Test Server
Mock of EPO OPS v3.2 for testing purposes. These end points are based on v
1.3.1 of the reference guide.

# Group Service Quota Errors
Test end points when user or app reaches OPS quota.

## IndividualQuotaPerHour exceeded [/individual-per-hour-exceeded/publication/docdb/biblio]
Each registered user account is allowed to use 450MB per hour.

### POST
+ Request

    ```
    (Forbidden).(Quota).(exceeded)
    ```
+ Response 403 (application/xml)
    + Headers

        ```
        X-Rejection-Reason: IndividualQuotaPerHour exceeded
        ```

    + Body
        ```
        <error><code>403</code><message>This request has been rejected due to the violation of Fair Use policy</message><moreInfo>http://www.epo.org/searching/free/espacenet/fair-use.html</moreInfo></error>
        ```

## RegisteredQuotaPerWeek exceeded [/registered-per-week-exceeded/publication/docdb/biblio]
Each free registered user account is allowed to use 2.5GB per week.

### POST
+ Request

    ```
    (Forbidden).(Quota).(exceeded)
    ```
+ Response 403 (application/xml)
    + Headers

        ```
        X-Rejection-Reason: RegisteredQuotaPerWeek
        ```

    + Body
        ```
        <error><code>403</code><message>This request has been rejected due to the violation of Fair Use policy</message><moreInfo>http://www.epo.org/searching/free/espacenet/fair-use.html</moreInfo></error>
        ```
